repos:
  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.37.3
      hooks:
      -   id: pyupgrade
          args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
